### ISSUE TITLE
Custom build of Pkcs11Interop library in 2.0.0 alpha packages

### ISSUE THREAD

**Issue by jariq** [pavelkhrulev/RutokenPkcs11Interop#31]
Hello Pavel,

I noticed that [Aktiv.RutokenPkcs11Interop 2.0.0-alpha1](https://www.nuget.org/packages/Aktiv.RutokenPkcs11Interop/2.0.0-alpha1) nuget package dropped reference to  [Pkcs11Interop](https://www.nuget.org/packages/Pkcs11Interop/) package and includes custom build of Pkcs11Interop library instead. I was wondering what was the reason for this change. Is there something you are missing in Pkcs11Interop package?

**Comment by pavelkhrulev** [comment]
Hi Jaroslav,
The only one reason to use custom build of your library is to refer to this [issue](https://github.com/Pkcs11Interop/Pkcs11Interop/issues/106).
So you can find changes in this [commit](https://github.com/pavelkhrulev/Pkcs11Interop/commit/5d0be8b530488ea30b73030303547c808a8cd466). I will be pleasure if you fix it in 4.1.1 version.

**Comment by jariq** [comment]
Sure, no problem, I'll take a look at it over the weekend. Did you test your changes with any real Android devices?

**Comment by pavelkhrulev** [comment]
Yes, I tested changes on Samsung Galaxy S8 with Android 8.1 on board. Your library works with my fix.

**Comment by jariq** [comment]
I published [Pkcs11Interop 4.1.1](https://www.nuget.org/packages/Pkcs11Interop/4.1.1). Could you please test if it works for you?

**Comment by pavelkhrulev** [comment]
Thank you.
I'll try it today.

**Comment by pavelkhrulev** [comment]
@jariq, it works! Thanks :)
