### ISSUE TITLE
Add Silverlight platform

### ISSUE THREAD

**Issue by pavelkhrulev** [pavelkhrulev/RutokenPkcs11Interop#8]

**Comment by jariq** [comment]
Adding support for Silverlight at this point is not worth it unless you have a commercial use case for it. I've already [dropped it](https://github.com/Pkcs11Interop/Pkcs11Interop/issues/72) from upcoming [Pkcs11Interop 5](https://github.com/Pkcs11Interop/Pkcs11Interop/projects/1).

**Comment by pavelkhrulev** [comment]
@jariq, Ok. Thanks for information!
